# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-24 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=20, verbose_name='身份证编号')),
                ('addr', models.CharField(default='千锋派出所', max_length=20)),
            ],
            options={
                'verbose_name': '身份证类',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='人名')),
                ('idcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app03_1.IdCard')),
            ],
        ),
    ]
