# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-24 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app03_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='班级名')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='学生名')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app03_1.Grade')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='idcard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app03_1.IdCard'),
        ),
    ]
