# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-24 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lianxi', '0002_grade_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'zd_phone',
            },
        ),
        migrations.CreateModel(
            name='Xinpian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'zd_xinpian',
            },
        ),
        migrations.AddField(
            model_name='phone',
            name='u',
            field=models.ManyToManyField(max_length=20, to='app_lianxi.Xinpian'),
        ),
    ]
