# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-24 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Humen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('age', models.IntegerField(default=1)),
                ('money', models.IntegerField(default=0)),
            ],
        ),
    ]
