# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-30 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app07', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engineer',
            options={'verbose_name': '工程师'},
        ),
        migrations.AddField(
            model_name='engineer',
            name='gender',
            field=models.BooleanField(default=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='age',
            field=models.IntegerField(verbose_name='年纪'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='name',
            field=models.CharField(max_length=30, verbose_name='名字'),
        ),
    ]
