# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-30 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app07', '0002_auto_20181030_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='公司名字')),
            ],
        ),
        migrations.AddField(
            model_name='engineer',
            name='company',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='app07.Company', verbose_name='公司id'),
        ),
    ]
