# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-30 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app07', '0003_auto_20181030_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='主题')),
                ('content', tinymce.models.HTMLField(verbose_name='内容')),
            ],
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '公司'},
        ),
    ]
